---
AllCops:
  Exclude:
  - vendor/**/*
Style/Encoding:
  Enabled: false
Documentation:
  Enabled: false
ParameterAlignment:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 42
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
# https://github.com/rubocop-hq/rubocop/issues/4198
Lint/AmbiguousBlockAssociation:
  Enabled: False
